logging:
  level:
    root: warn
    hm.binkley: info

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false  # Hibernate needs "show_sql" rather than "show-sql"
    show-sql: false
  main:
    banner-mode: 'OFF'  # case-sensitive, plain "OFF" is treated as 'false'
  output:
    ansi:
      enabled: always
